### ISSUE TITLE
Can VOSviewer read XML files and generate maps

### ISSUE THREAD

**Issue by alexmaina** [seinecle/vosviewer-tutorials#1]
Hello, 
Can i import XML file containing keywords into VOSviewer and  do co-word analysis?

**Comment by seinecle** [comment]
No, you need a file formatted in this simple way each unit of text must be on one line.

So, if you have a list of keywords, format them like this:

keyword1 keyword2 keyword3
keyword3 keyword5 keyword4 keyword6 keyword7
keyword3 keyword4 keyword2 keyword4 keyword8
keyword2 keyword1 keyword3 keyword7 keyword4 keyword5 keyword6
etc...

And Vosviewer will produce a map of keywords, based on how they cooccur on each line.

**Comment by alexmaina** [comment]
So you are saying that i need to create a new line for each of my XML elements.. No?

**Comment by seinecle** [comment]
Yes. If you have something like:
```xml
<keywords>keywords1 keywords2 keywords3</keywords>
<keywords>keywords3 keywords1 keywords4</keywords>
```
etc...

Then you need to turn it into

keywords1 keywords2 keywords3
keywords3 keywords1 keywords4

**Comment by alexmaina** [comment]
Thank you
