### ISSUE TITLE
How do you input Pubmed data inoto VOSviewer

### ISSUE THREAD

**Issue by alexmaina** [seinecle/vosviewer-tutorials#2]
I have just finished reading the VOSviewer manual. It states that one can imput Scopus, Pubmed, RIS data etc into VOSViewer. My question is..... in what format does one import pubmed data into VOSviewer? Is it in MEDLINE format, summary format, abstract format?

**Comment by seinecle** [comment]
MEDLINE format

**Comment by alexmaina** [comment]
Thank you
